# 配置Spring框架的属性
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.20.103:3306/rumo?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: dms01
    password: Cse@dms01

# 配置系统ORM映射框架
mybatis:
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
  type-aliases-package: cn.edu.qfnu.meta.model.domain
  mapper-locations: classpath:mappers/*.xml

# 配置系统日志
logging:
  level:
    cn.edu.qfnu.rumo.repository: debug



#druid:
#  type: com.alibaba.druid.pool.DruidDataSource
#  master:
#    url: jdbc:mysql://10.10.20.103:3306/rumo-master?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
#    username: dms01
#    password: Cse@dms01
#    initial-size: 5
#    min-idle: 1
#    max-active: 100
#    test-on-borrow: true
#  slave:
#    url: jdbc:mysql://10.10.20.103:3306/rumo-slave?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
#    username: dms01
#    password: Cse@dms01
#    initial-size: 5
#    min-idle: 1
#    max-active: 100
#    test-on-borrow: true
